### ISSUE TITLE
Testing docker-compose leads to error

### ISSUE THREAD

**Issue by straussmaximilian** [biocypher/meta-graph#5]
Hi, I was testing the meta-graph, but encountered the following error.
This is from a Linux VM:

```
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-146-generic x86_64)
```

```
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:21 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:04 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Any clue where this could be coming from?

Thanks!

Full log:
```
(base) root@ckg:~/meta-graph# docker compose up
[+] Running 1/0
 ✔ Container biocypher-project-template-container  Created                                                                                                                                                                        0.0s 
Attaching to biocypher-project-template-container
biocypher-project-template-container  | Selecting JVM - Version:11.0.18+10, Name:OpenJDK 64-Bit Server VM, Vendor:Eclipse Adoptium
biocypher-project-template-container  | Neo4j version: 4.4.19
biocypher-project-template-container  | Importing the contents of these files into /data/databases/docker:
biocypher-project-template-container  | Nodes:
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/AdapterInputFormat-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/AdapterInputFormat-part000.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/Pipeline-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/Pipeline-part000.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/ResourceType-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/ResourceType-part000.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/SecondaryInputAdapter-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/SecondaryInputAdapter-part000.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/PrimaryOutputAdapter-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/PrimaryOutputAdapter-part000.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/PrimaryOntologyAdapter-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/PrimaryOntologyAdapter-part000.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/DataType-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/DataType-part000.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/PrimaryInputAdapter-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/PrimaryInputAdapter-part000.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/SecondaryOntologyAdapter-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/SecondaryOntologyAdapter-part000.csv
biocypher-project-template-container  | 
biocypher-project-template-container  | Relationships:
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/IsPartOf-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/IsPartOf-part000.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/Uses-header.csv
biocypher-project-template-container  |   /var/lib/neo4j/import/docker/Uses-part000.csv
biocypher-project-template-container  | 
biocypher-project-template-container  | 
biocypher-project-template-container  | Available resources:
biocypher-project-template-container  |   Total machine memory: 7.771GiB
biocypher-project-template-container  |   Free machine memory: 3.125GiB
biocypher-project-template-container  |   Max heap memory : 1.943GiB
biocypher-project-template-container  |   Processors: 4
biocypher-project-template-container  |   Configured max memory: 5.245GiB
biocypher-project-template-container  |   High-IO: true
biocypher-project-template-container  | 
biocypher-project-template-container  | 
biocypher-project-template-container  | Import starting 2023-04-17 20:29:54.901+0000
biocypher-project-template-container  |   Estimated number of nodes: 65.00 
biocypher-project-template-container  |   Estimated number of node properties: 227.00 
biocypher-project-template-container  |   Estimated number of relationships: 132.00 
biocypher-project-template-container  |   Estimated number of relationship properties: 0.00 
biocypher-project-template-container  |   Estimated disk space usage: 13.66KiB
biocypher-project-template-container  |   Estimated required memory usage: 1020MiB
biocypher-project-template-container  | 
biocypher-project-template-container  | (1/4) Node import 2023-04-17 20:29:54.979+0000
biocypher-project-template-container  |   Estimated number of nodes: 65.00 
biocypher-project-template-container  |   Estimated disk space usage: 9.277KiB
biocypher-project-template-container  |   Estimated required memory usage: 1020MiB
biocypher-project-template-container  | -......... .......... .......... .......... ..........   5% ∆46ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  10% ∆2ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  15% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  20% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  25% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  30% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  35% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  40% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  45% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  50% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  55% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  60% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  65% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  70% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  75% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  80% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  85% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  90% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  95% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... .......... 100% ∆5ms
biocypher-project-template-container  | 
biocypher-project-template-container  | Node import COMPLETED in 173ms
biocypher-project-template-container  | 
biocypher-project-template-container  | (2/4) Relationship import 2023-04-17 20:29:55.153+0000
biocypher-project-template-container  |   Estimated number of relationships: 132.00 
biocypher-project-template-container  |   Estimated disk space usage: 4.383KiB
biocypher-project-template-container  |   Estimated required memory usage: 1.004GiB
biocypher-project-template-container  | .......... .......... .......... .......... ..........   5% ∆74ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  10% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  15% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  20% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  25% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  30% ∆8ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  35% ∆8ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  40% ∆8ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  45% ∆6ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  50% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  55% ∆12ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  60% ∆8ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  65% ∆8ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  70% ∆4ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  75% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  80% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  85% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  90% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  95% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... .......... 100% ∆0ms
biocypher-project-template-container  | 
biocypher-project-template-container  | Relationship import COMPLETED in 139ms
biocypher-project-template-container  | 
biocypher-project-template-container  | (3/4) Relationship linking 2023-04-17 20:29:55.292+0000
biocypher-project-template-container  |   Estimated required memory usage: 1020MiB
biocypher-project-template-container  | -......... .......... .......... .......... ..........   5% ∆99ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  10% ∆2ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  15% ∆2ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  20% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  25% ∆3ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  30% ∆8ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  35% ∆6ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  40% ∆7ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  45% ∆5ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  50% ∆5ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  55% ∆5ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  60% ∆5ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  65% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  70% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  75% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  80% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  85% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  90% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  95% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... .......... 100% ∆1ms
biocypher-project-template-container  | 
biocypher-project-template-container  | Relationship linking COMPLETED in 406ms
biocypher-project-template-container  | 
biocypher-project-template-container  | (4/4) Post processing 2023-04-17 20:29:55.699+0000
biocypher-project-template-container  |   Estimated required memory usage: 1020MiB
biocypher-project-template-container  | -......... .......... .......... .......... ..........   5% ∆192ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  10% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  15% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  20% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  25% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  30% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  35% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  40% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  45% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  50% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  55% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  60% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  65% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  70% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  75% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  80% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  85% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  90% ∆1ms
biocypher-project-template-container  | .......... .......... .......... .......... ..........  95% ∆0ms
biocypher-project-template-container  | .......... .......... .......... .......... .......... 100% ∆1ms
biocypher-project-template-container  | 
biocypher-project-template-container  | Post processing COMPLETED in 711ms
biocypher-project-template-container  | 
biocypher-project-template-container  | 
biocypher-project-template-container  | IMPORT DONE in 1s 620ms. 
biocypher-project-template-container  | Imported:
biocypher-project-template-container  |   65 nodes
biocypher-project-template-container  |   132 relationships
biocypher-project-template-container  |   227 properties
biocypher-project-template-container  | Peak memory usage: 1.004GiB
biocypher-project-template-container  | Warning: Some files inside "/data" are not writable from inside container. Changing folder owner to neo4j.
biocypher-project-template-container  | Changed password for user 'neo4j'. IMPORTANT: this change will only take effect if performed before the database is started for the first time.
biocypher-project-template-container  | 2023-04-17 20:30:03.150+0000 WARN  Unrecognized setting. No declared setting with name: PASSWORD
biocypher-project-template-container  | 2023-04-17 20:30:03.151+0000 WARN  Unrecognized setting. No declared setting with name: USER
biocypher-project-template-container  | 2023-04-17 20:30:03.171+0000 INFO  Starting...
biocypher-project-template-container  | 2023-04-17 20:30:03.709+0000 ERROR Failed to start Neo4j on 0.0.0.0:7474.
biocypher-project-template-container  | java.lang.RuntimeException: java.io.EOFException
biocypher-project-template-container  | 	at org.neo4j.dbms.identity.AbstractIdentityModule.readOrGenerate(AbstractIdentityModule.java:69) ~[neo4j-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.dbms.identity.DefaultIdentityModule.<init>(DefaultIdentityModule.java:46) ~[neo4j-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.dbms.identity.DefaultIdentityModule.fromGlobalModule(DefaultIdentityModule.java:39) ~[neo4j-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.graphdb.factory.module.edition.CommunityEditionModule.<init>(CommunityEditionModule.java:146) ~[neo4j-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at com.neo4j.enterprise.edition.EnterpriseEditionModule.<init>(EnterpriseEditionModule.java:150) ~[neo4j-enterprise-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at com.neo4j.enterprise.edition.EnterpriseEditionModule.<init>(EnterpriseEditionModule.java:145) ~[neo4j-enterprise-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:134) ~[neo4j-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at com.neo4j.server.enterprise.EnterpriseManagementServiceFactory.createManagementService(EnterpriseManagementServiceFactory.java:38) ~[neo4j-enterprise-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at com.neo4j.server.enterprise.EnterpriseBootstrapper.createNeo(EnterpriseBootstrapper.java:20) ~[neo4j-enterprise-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:142) [neo4j-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:95) [neo4j-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at com.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:24) [neo4j-enterprise-4.4.19.jar:4.4.19]
biocypher-project-template-container  | Caused by: java.io.EOFException
biocypher-project-template-container  | 	at java.io.DataInputStream.readByte(DataInputStream.java:272) ~[?:?]
biocypher-project-template-container  | 	at org.neo4j.io.fs.InputStreamReadableChannel.get(InputStreamReadableChannel.java:38) ~[neo4j-io-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.dbms.identity.ServerId$Marshal.unmarshal0(ServerId.java:74) ~[neo4j-kernel-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.dbms.identity.ServerId$Marshal.unmarshal0(ServerId.java:47) ~[neo4j-kernel-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.io.marshal.SafeChannelMarshal.unmarshal(SafeChannelMarshal.java:40) ~[neo4j-io-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.io.state.SimpleFileStorage.readState(SimpleFileStorage.java:57) ~[neo4j-io-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	at org.neo4j.dbms.identity.AbstractIdentityModule.readOrGenerate(AbstractIdentityModule.java:47) ~[neo4j-4.4.19.jar:4.4.19]
biocypher-project-template-container  | 	... 11 more
biocypher-project-template-container  | 2023-04-17 20:30:03.721+0000 INFO  Neo4j Server shutdown initiated by request
biocypher-project-template-container  | 2023-04-17 20:30:03.721+0000 INFO  Stopped.
biocypher-project-template-container exited with code 1
(base) root@ckg:~/meta-graph# 
```

**Comment by slobentanzer** [comment]
Hi @straussmaximilian,
that's interesting, for me it still runs fine. Maybe you changed something locally or have an older conflicting version lying around? You seem to be starting only the final container in this run, can you clear your Docker environment of all remnants and try again?

Are you on `main`? You can also try the build on the `read_only` branch, which is what we currently use to build the web version of the metagraph (https://meta.biocypher.org). That Docker setup is also a bit more mature. You can omit the last, read-only step if you want a modifiable local graph.
